version: 2.1

orbs:
  maven: circleci/maven@0.0.12

steps: 
   -checkout: ./FreeNowCodingChallenge/feature
   -run: mvn dependency:go-offline
   

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      
      
      
  
      
      
