version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  
workflows:
  maven_test:
    jobs:
      - maven/test --settings 'FreeNowCodingChallenge/pom.xml' # checkout, build, test, and upload test results
      
      
      
  
      
      
