version: 2.1

orbs:
  maven: circleci/maven@0.0.12

steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "./pom.xml" }}-{{ checksum  "FreeNowCodingChallenge/pom.xml" }}
   

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      
      
      
  
      
      
