version: 2.1

orbs:
  maven: circleci/maven@0.0.12
parameters:
  settings_file:
    description: Specify a custom settings file to use (optional)
    type: string
    default: "FreeNowCodingChallenge"

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      
      
      
  
      
      
